name: Create Repository

on:
  issues:
    types: 
      - opened
env:
  ORG: 'A1EBD7CC0EB3'
jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'repo-creation')
    steps:
      - uses: actions/checkout@v3

      ## validate the deetz
      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/repo_creation.yaml
      
      # Dont run if a field is empty
      - name: Test variables
        run: |
          if [[ -z "${{ steps.issue-parser.outputs.issueparser_name }}" || -z "${{ steps.issue-parser.outputs.issueparser_template }}" ]]; then
            echo Please submit a new issue and fill out ALL the fields
            exit 1
          fi
          ## Todo write this to the issue, maybe allow a /rerun command

      # Check if repo by the name already exists and notify in issue/exit if it does
      - name: Checking for repo existance
        run: |
          echo do something
      
      - name: Create repo
        id: createRepo
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          # do this https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-using-a-template
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ steps.issue-parser.outputs.issueparser_template }}/generate \
            -f owner='${{ env.ORG }}' \
           -f name='${{ steps.issue-parser.outputs.issueparser_name }}' \
           -f description='This a generated repo' \
           -F include_all_branches=false \
           -F private=true

      - name: Comment success
        if: steps.build.outcome == 'success'
        run: |
          # Comment back to issue & close issue
          echo "success todo"

      - name: Comment failure
        if: steps.build.outcome != 'success'
        run: |
          # Comment back to issue & fail
          echo "failure todo"
          exit 1

      - name: TODO Add users/teams permissions to repo
        if: steps.build.outcome == 'success'
        run: |
          # Comment back to issue & close issue. Add Github.actor as admin, add teams specified
          echo "teams todo"

