name: Create Repository

on:
  issues:
    types: 
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'repo-creation')
    steps:
      - uses: actions/checkout@v3

      ## validate the deetz
      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/repo_creation.yaml
      
      # Dont run if a field is empty
      - name: Test variables
        run: |
          if [[ -z "${{ steps.issue-parser.outputs.issueparser_name }}" || -z "${{ steps.issue-parser.outputs.issueparser_template }}" ]]; then
            echo Please submit a new issue and fill out ALL the fields
            exit 1
          fi
          ## Todo write this to the issue, maybe allow a /rerun command

      # Check if repo by the name already exists and notify in issue/exit if it does
      - name: Checking for repo existance
        run: |
          echo do something
      
      - name: Create repo
        run: |
          # do this https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-using-a-template
          echo gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/TEMPLATE_OWNER/TEMPLATE_REPO/generate \
            -f owner='octocat' \
           -f name='Hello-World' \
           -f description='This is your first repository' \
           -F include_all_branches=false \
           -F private=false 
